apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -tdx

resources:
- ../base

images:
- name: quay.io/confidential-containers/reqs-payload
  newTag: latest
- name: quay.io/kata-containers/kata-deploy
  newName: quay.io/kata-containers/kata-deploy
  newTag: stable-3.11.0

patches:
# Patch to disable the pre-install daemon
- patch: |-
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: cc-operator-pre-install-daemon
      namespace: confidential-containers-system
    spec:
      template:
        spec:
          containers:
          - name: cc-operator-pre-install-daemon
            env:
            - name: "NODE_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              set -e
              
              echo "RKE2/K3s compatible pre-install daemon"
              echo "This daemon will not install any artifacts or restart containerd"
              
              # Create a fake containerd to prevent restart
              mkdir -p /usr/local/bin
              cat > /usr/local/bin/containerd << 'EOF'
              #!/bin/bash
              echo "Fake containerd - preventing restart"
              exit 0
              EOF
              chmod +x /usr/local/bin/containerd
              
              # Label the node as done without doing anything
              kubectl label node "${NODE_NAME}" confidentialcontainers.org/preinstall=done --overwrite
              
              echo "Node labeled, sleeping indefinitely"
              sleep infinity
  target:
    kind: DaemonSet
    name: cc-operator-pre-install-daemon
    namespace: confidential-containers-system

# Configure the CcRuntime
- patch: |-
    - op: replace
      path: /spec/config/runtimeClasses
      value:
      - name: "kata-qemu-tdx"
        snapshotter: ""
        pulltype: ""
      - name: "kata-qemu"
        snapshotter: ""
        pulltype: ""
    - op: add
      path: /spec/config/debug
      value: true
    - op: add
      path: /spec/config/environmentVariables
      value:
        - name: "INSTALL_OFFICIAL_CONTAINERD"
          value: "false"
        - name: "INSTALL_COCO_CONTAINERD"
          value: "false"
        - name: "INSTALL_VFIO_GPU_CONTAINERD"
          value: "false"
        - name: "INSTALL_NYDUS_SNAPSHOTTER"
          value: "false"
        - name: "CONFIGURE_CC"
          value: "yes"
        - name: "DEBUG"
          value: "true"
    - op: replace
      path: /spec/config/installCmd
      value: 
      - /bin/bash
      - -c
      - |
        set -ex
        echo "Installing Kata for RKE2/K3s with TDX support..."
        
        # First, let's find where kata files actually are in this container
        echo "=== Finding kata files in container ==="
        echo "Looking for kata-runtime binary anywhere in container:"
        find / -type f -name "kata-runtime" 2>/dev/null || true
        
        echo "Looking for kata directories:"
        find / -type d -name "*kata*" -o -name "*artifacts*" 2>/dev/null | grep -v proc | head -20 || true
        
        echo "Contents of /opt:"
        ls -la /opt/ || true
        
        echo "Contents of root directory:"
        ls -la / || true
        
        # Check if kata binaries are in the standard location for kata-deploy
        if [ -d "/opt/kata" ]; then
          echo "Found /opt/kata in container"
          ls -la /opt/kata/
        fi
        
        # Detect containerd config location
        if [ -d "/var/lib/rancher/rke2" ]; then
          CONFIG_PATH="/var/lib/rancher/rke2/agent/etc/containerd"
          CONFIG_FILE="$CONFIG_PATH/config.toml.tmpl"
          RUNTIME_TYPE="rke2"
          echo "Detected RKE2"
        elif [ -d "/var/lib/rancher/k3s" ]; then
          CONFIG_PATH="/var/lib/rancher/k3s/agent/etc/containerd"
          CONFIG_FILE="$CONFIG_PATH/config.toml.tmpl"
          RUNTIME_TYPE="k3s"
          echo "Detected K3s"
        else
          CONFIG_PATH="/etc/containerd"
          CONFIG_FILE="$CONFIG_PATH/config.toml"
          RUNTIME_TYPE="standard"
          echo "Using standard containerd path"
        fi
        
        # Install kata binaries - try multiple possible locations
        echo "=== Installing kata binaries ==="
        KATA_INSTALLED=false
        
        # Try location 1: Direct copy from container's /opt/kata
        if [ -d "/opt/kata" ] && [ -f "/opt/kata/bin/kata-runtime" ]; then
          echo "Found kata in container at /opt/kata"
          # The kata files are already in the container, no need to copy from artifacts
          KATA_INSTALLED=true
        # Try location 2: From kata-artifacts volume
        elif [ -d "/opt/kata-artifacts/opt/kata" ]; then
          echo "Found kata at /opt/kata-artifacts/opt/kata"
          mkdir -p /opt
          cp -a /opt/kata-artifacts/opt/kata /opt/
          KATA_INSTALLED=true
        # Try location 3: Look for any kata directory
        else
          echo "Searching for kata files..."
          KATA_DIR=$(find /opt -type d -name "kata" 2>/dev/null | grep -v artifacts | head -1)
          if [ -n "$KATA_DIR" ] && [ -f "$KATA_DIR/bin/kata-runtime" ]; then
            echo "Found kata at: $KATA_DIR"
            if [ "$KATA_DIR" != "/opt/kata" ]; then
              cp -a "$KATA_DIR" /opt/kata
            fi
            KATA_INSTALLED=true
          fi
        fi
        
        if [ "$KATA_INSTALLED" = false ]; then
          echo "ERROR: Cannot find kata installation files!"
          echo "This kata-deploy image might not contain the expected files."
          echo "Trying alternative approach..."
          
          # Alternative: Download kata release directly
          echo "Downloading kata release..."
          ARCH=$(uname -m)
          KATA_VERSION="3.11.0"
          if [ "$ARCH" = "x86_64" ]; then
            wget -q "https://github.com/kata-containers/kata-containers/releases/download/${KATA_VERSION}/kata-static-${KATA_VERSION}-${ARCH}.tar.xz" -O /tmp/kata.tar.xz
            mkdir -p /opt
            tar -xf /tmp/kata.tar.xz -C /opt
            rm /tmp/kata.tar.xz
            KATA_INSTALLED=true
          else
            echo "FATAL: Unsupported architecture: $ARCH"
            exit 1
          fi
        fi
        
        # Ensure permissions
        chmod +x /opt/kata/bin/* || true
        
        # Create symlinks
        echo "=== Creating symlinks ==="
        mkdir -p /usr/local/bin
        ln -sf /opt/kata/bin/kata-runtime /usr/local/bin/kata-runtime
        ln -sf /opt/kata/bin/containerd-shim-kata-v2 /usr/local/bin/containerd-shim-kata-v2
        ln -sf /opt/kata/bin/kata-collect-data.sh /usr/local/bin/kata-collect-data.sh || true
        
        # Verify binaries are executable
        echo "=== Verifying kata installation ==="
        if [ -f "/opt/kata/bin/kata-runtime" ]; then
          /opt/kata/bin/kata-runtime --version || echo "WARNING: kata-runtime not executable"
        else
          echo "ERROR: kata-runtime not found at /opt/kata/bin/kata-runtime"
          ls -la /opt/kata/bin/ || echo "ERROR: /opt/kata/bin/ not found"
        fi
        
        # Create kata configuration directory
        echo "=== Setting up kata configuration ==="
        mkdir -p /etc/kata-containers/
        
        # Find and link the configuration
        CONFIG_SOURCE="/opt/kata/share/defaults/kata-containers/configuration.toml"
        if [ -f "$CONFIG_SOURCE" ]; then
          ln -sf "$CONFIG_SOURCE" /etc/kata-containers/configuration.toml
        else
          echo "WARNING: Default configuration not found at $CONFIG_SOURCE"
          echo "Looking for configuration files:"
          find /opt/kata -name "configuration*.toml" -type f 2>/dev/null || true
        fi
        
        # Create TDX-specific configuration
        echo "=== Creating TDX configuration ==="
        mkdir -p /opt/kata/share/defaults/kata-containers/
        TDX_CONFIG="/opt/kata/share/defaults/kata-containers/configuration-qemu-tdx.toml"
        QEMU_CONFIG="/opt/kata/share/defaults/kata-containers/configuration-qemu.toml"
        BASE_CONFIG="/opt/kata/share/defaults/kata-containers/configuration.toml"
        
        # Find a base configuration to copy
        if [ -f "$QEMU_CONFIG" ]; then
          cp "$QEMU_CONFIG" "$TDX_CONFIG"
        elif [ -f "$BASE_CONFIG" ]; then
          cp "$BASE_CONFIG" "$TDX_CONFIG"
        else
          echo "WARNING: No base configuration found, creating minimal TDX config"
          cat > "$TDX_CONFIG" << 'EOFMINIMAL'
        # Kata TDX Configuration
        [hypervisor.qemu]
        path = "/opt/kata/bin/qemu-system-x86_64"
        kernel = "/opt/kata/share/kata-containers/vmlinuz.container"
        image = "/opt/kata/share/kata-containers/kata-containers.img"
        machine_type = "q35"
        confidential_guest = true
        tdx = true
        kernel_params = "agent.log=debug tdx_guest=on"
        default_vcpus = 1
        default_memory = 2048
        
        [agent.kata]
        enable_debug = true
        
        [runtime]
        enable_debug = true
        EOFMINIMAL
        fi
        
        # Add/Update TDX-specific settings
        echo "=== Configuring TDX settings ==="
        if ! grep -q "confidential_guest = true" "$TDX_CONFIG" 2>/dev/null; then
          cat >> "$TDX_CONFIG" << 'EOFTDX'

        # TDX Configuration Section
        [hypervisor.qemu]
        confidential_guest = true
        tdx = true
        kernel_params = " tdx_guest=on"
        EOFTDX
        fi
        
        # Update containerd config
        echo "=== Updating containerd configuration ==="
        mkdir -p "$CONFIG_PATH"
        
        # Check if kata is already configured
        if [ -f "$CONFIG_FILE" ] && ! grep -q "kata-qemu-tdx" "$CONFIG_FILE"; then
          echo "Adding kata runtime configurations..."
          
          # Add kata runtimes configuration
          cat >> "$CONFIG_FILE" << 'EOFKATA'

        # Kata Containers Runtimes
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata]
          runtime_type = "io.containerd.kata.v2"
          privileged_without_host_devices = true
          pod_annotations = ["io.katacontainers.*"]
          container_annotations = ["io.katacontainers.*"]
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata.options]
            ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration.toml"

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu]
          runtime_type = "io.containerd.kata.v2"
          privileged_without_host_devices = true
          pod_annotations = ["io.katacontainers.*"]
          container_annotations = ["io.katacontainers.*"]
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu.options]
            ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration-qemu.toml"

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu-tdx]
          runtime_type = "io.containerd.kata.v2"
          privileged_without_host_devices = true
          pod_annotations = ["io.katacontainers.*"]
          container_annotations = ["io.katacontainers.*"]
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu-tdx.options]
            ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration-qemu-tdx.toml"
        EOFKATA
        else
          echo "Kata runtimes already configured in containerd"
        fi
        
        echo "=== Installation Summary ==="
        echo "Kata binaries installed at: /opt/kata"
        echo "Configuration updated at: $CONFIG_FILE"
        echo "Runtime type: $RUNTIME_TYPE"
        echo "TDX configuration created at: $TDX_CONFIG"
        
        # Final verification
        echo "=== Final verification ==="
        ls -la /opt/kata/bin/kata-runtime || echo "ERROR: kata-runtime not found"
        ls -la /usr/local/bin/kata-runtime || echo "ERROR: kata-runtime symlink not found"
        ls -la "$TDX_CONFIG" || echo "WARNING: TDX config not found"
        
        echo ""
        echo "============================================"
        echo "=== IMPORTANT: Manual restart required ==="
        echo "============================================"
        echo "Kata installation completed successfully!"
        echo ""
        echo "You MUST manually restart your container runtime:"
        echo "  For RKE2 server: sudo systemctl restart rke2-server"
        echo "  For RKE2 agent: sudo systemctl restart rke2-agent"
        echo "  For K3s: sudo systemctl restart k3s or k3s-agent"
        echo "============================================"
        echo ""
        
        # Create marker file
        touch /opt/kata/.installed
        echo "Installation completed at $(date)" > /opt/kata/.installed
    - op: replace
      path: /spec/config/uninstallCmd
      value:
      - /bin/bash
      - -c
      - |
        echo "Uninstalling Kata..."
        rm -rf /opt/kata
        rm -f /usr/local/bin/kata-runtime
        rm -f /usr/local/bin/containerd-shim-kata-v2
        rm -f /usr/local/bin/kata-collect-data.sh
        rm -rf /etc/kata-containers
        rm -f /opt/kata/.installed
        echo "Kata uninstalled"
    - op: replace
      path: /spec/config/installerVolumes
      value:
        - hostPath:
            path: /opt/kata-artifacts/
            type: DirectoryOrCreate
          name: kata-artifacts
        - hostPath:
            path: /var/lib/rancher/rke2/agent/etc/containerd/
            type: DirectoryOrCreate
          name: rke2-containerd-conf
        - hostPath:
            path: /var/lib/rancher/k3s/agent/etc/containerd/
            type: DirectoryOrCreate
          name: k3s-containerd-conf
        - hostPath:
            path: /etc/containerd/
            type: DirectoryOrCreate
          name: containerd-conf
        - hostPath:
            path: /usr/local/bin/
            type: DirectoryOrCreate
          name: local-bin
        - hostPath:
            path: /opt/
            type: DirectoryOrCreate
          name: opt-dir
        - hostPath:
            path: /etc/kata-containers/
            type: DirectoryOrCreate
          name: kata-config-dir
    - op: replace
      path: /spec/config/installerVolumeMounts
      value:
        - mountPath: /opt/kata-artifacts/
          name: kata-artifacts
        - mountPath: /var/lib/rancher/rke2/agent/etc/containerd/
          name: rke2-containerd-conf
        - mountPath: /var/lib/rancher/k3s/agent/etc/containerd/
          name: k3s-containerd-conf
        - mountPath: /etc/containerd/
          name: containerd-conf
        - mountPath: /usr/local/bin/
          name: local-bin
        - mountPath: /opt/
          name: opt-dir
        - mountPath: /etc/kata-containers/
          name: kata-config-dir
    - op: add
      path: /spec/ccNodeSelector
      value:
        matchLabels:
          node-role.kubernetes.io/worker: "true"
  target:
    kind: CcRuntime
    name: ccruntime