apiVersion: confidentialcontainers.org/v1beta1
kind: CcRuntime
metadata:
  name: ccruntime-sample
spec:
  runtimeName: kata
  ccNodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker: ""
  config:
    installType: bundle
    payloadImage: quay.io/kata-containers/kata-deploy:stable
    installDoneLabel:
      katacontainers.io/kata-runtime: "true"
    uninstallDoneLabel:
      katacontainers.io/kata-runtime: "cleanup"
    installerVolumeMounts:
      # RKE2 uses a different containerd path
      - mountPath: /var/lib/rancher/rke2/agent/etc/containerd/
        name: rke2-containerd-conf
      - mountPath: /usr/local/bin/
        name: local-bin
      - mountPath: /host/
        name: host
      # Add RKE2 specific paths
      - mountPath: /var/lib/rancher/rke2/
        name: rke2-root
      - mountPath: /run/k3s/containerd/
        name: containerd-socket
    installerVolumes:
      - hostPath:
          path: /var/lib/rancher/rke2/agent/etc/containerd/
          type: ""
        name: rke2-containerd-conf
      - hostPath:
          path: /usr/local/bin/
          type: ""
        name: local-bin
      - hostPath:
          path: /
          type: ""
        name: host
      # Add RKE2 specific volumes
      - hostPath:
          path: /var/lib/rancher/rke2/
          type: ""
        name: rke2-root
      - hostPath:
          path: /run/k3s/containerd/
          type: ""
        name: containerd-socket
    installCmd: ["/opt/kata-artifacts/scripts/kata-deploy.sh", "install"]
    uninstallCmd: ["/opt/kata-artifacts/scripts/kata-deploy.sh", "cleanup"]
    cleanupCmd: ["/opt/kata-artifacts/scripts/kata-deploy.sh", "reset"]
    runtimeClasses: 
      []
    preInstall:
      image: quay.io/confidential-containers/reqs-payload
      volumeMounts:
        - mountPath: /opt/confidential-containers/
          name: confidential-containers-artifacts
        - mountPath: /var/lib/rancher/rke2/agent/etc/containerd/
          name: rke2-containerd-conf
        - mountPath: /usr/local/bin/
          name: local-bin
        # Add RKE2 specific mounts
        - mountPath: /var/lib/rancher/rke2/
          name: rke2-root
        - mountPath: /run/k3s/containerd/
          name: containerd-socket
      volumes:
        - hostPath:
            path: /opt/confidential-containers/
            type: DirectoryOrCreate
          name: confidential-containers-artifacts
        - hostPath:
            path: /var/lib/rancher/rke2/agent/etc/containerd/
            type: ""
          name: rke2-containerd-conf
        - hostPath:
            path: /usr/local/bin/
            type: ""
          name: local-bin
        # Add RKE2 specific volumes
        - hostPath:
            path: /var/lib/rancher/rke2/
            type: ""
          name: rke2-root
        - hostPath:
            path: /run/k3s/containerd/
            type: ""
          name: containerd-socket
    environmentVariables:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.nodeName
      - name: "CONFIGURE_CC"
        value: "yes"
      - name: "DEBUG"
        value: "true"
      # Disable all containerd installations since RKE2 manages its own containerd
      - name: "INSTALL_COCO_CONTAINERD"
        value: "false"
      - name: "INSTALL_OFFICIAL_CONTAINERD"
        value: "false"
      - name: "INSTALL_VFIO_GPU_CONTAINERD"
        value: "false"
      - name: "INSTALL_NYDUS_SNAPSHOTTER"
        value: "false"
      # Add RKE2-specific variables
      - name: "CONTAINERD_CONFIG_PATH"
        value: "/var/lib/rancher/rke2/agent/etc/containerd/config.toml.d"
      - name: "CONTAINERD_SOCKET_PATH"
        value: "/run/k3s/containerd/containerd.sock"
      - name: "SYSTEMD_SERVICE_DIR"
        value: "/etc/systemd/system"
      - name: "IS_RKE2_NODE"
        value: "true"